name: Test setup-sfdx-action Funtionality

on:
  push:
  pull_request_target:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v7 #Check out this repo
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Install SFDX CLI and authorize DevHub
        uses: ./ #We're using a fork of https://github.com/sfdx-actions/setup-sfdx for safety
        with:
          sfdx-auth-url: ${{ secrets.DEVHUB_SFDXURL }}
      - run: sf force config set --global target-dev-hub=SFDX-ENV #Even though the setup-sfdx action uses --setdefaultdevhubusername, it doesn't seem to stick since it uses --setdefaultusername so we brute force it here
      #- run: sf force org create -f ./config/project-scratch-def.json --setdefaultusername -d 1
      #- run: sf force source push
      #- run: sf force apex test run -w 5
      #git clone fflib sample
      - name: Check Auth Orgs
        run: sf org list --json
        if: always()